; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                  = 10210118-x86_64 MS Windows          
[ DataSettings ]
datatype                             = snNucleotide                        
containsCodingNuc                    = False                               
MissingBaseSymbol                    = ?                                   
IdenticalBaseSymbol                  = .                                   
GapSymbol                            = -                                   
Labelled Sites                       = All Sites                           
Labels to Include                    =                                     
[ ProcessTypes ]
ppInfer                              = true                                
ppML                                 = true                                
[ AnalysisSettings ]
Analysis                             = Phylogeny Reconstruction            
Statistical Method                   = Maximum Likelihood                  
Phylogeny Test                       = ====================                
Test of Phylogeny                    = None                                
No. of Bootstrap Replications        = Not Applicable                      
Substitution Model                   = ====================                
Substitutions Type                   = Nucleotide                          
Model/Method                         = General Time Reversible model       
Rates and Patterns                   = ====================                
Rates among Sites                    = Gamma Distributed (G)               
No of Discrete Gamma Categories      = 5                                   
Data Subset to Use                   = ====================                
Gaps/Missing Data Treatment          = Partial deletion                    
Site Coverage Cutoff (%)             = 60                                  
Tree Inference Options               = ====================                
ML Heuristic Method                  = Nearest-Neighbor-Interchange (NNI)  
Initial Tree for ML                  = Make initial tree automatically (Default - NJ/BioNJ)
Branch Swap Filter                   = None                                
System Resource Usage                = ====================                
Number of Threads                    = 7                                   
Has Time Limit                       = False                               
Maximum Execution Time               = -1                                  
